src/main/scala/Main.scala
src/main/scala/analysis/TestingAnalysis.scala
src/main/scala/analysis/Worklist.scala
src/main/scala/translating/BoogieTranslator.scala
src/main/scala/translating/FlowGraph.scala

note known errors:
basicfree (in BoogieTranslator, resolveOutParams)
nestedifglobal (in parsing section of main, Walker.walk)

merge functioning block worklist into main

---

src/main/scala/analysis/Cfg.scala

https://github.com/UQ-PAC/bil-to-boogie-translator/issues/56

BASIL-56: Fixed single return call issue

---

src/main/scala/translating/BAPToIR.scala

Addresses https://github.com/UQ-PAC/bil-to-boogie-translator/issues/151

151; fix goto condition translation

---

src/main/scala/translating/SpecificationLoader.scala

Lets you refer to registers in existing spec language by naive pattern match on the name of idents.

registers in spec

---

scripts/format_adt.py

aslt is almost python. this adds support for semicolon separation, single-quote strings, and adds rules for line breaking aslt stmt/exprs.
example output:
[asl2.txt](https://github.com/UQ-PAC/bil-to-boogie-translator/files/14927565/asl2.txt)

patch format_adt.py for aslt format.

---

docs/basil-ir.md

Updates docs in accordance with recent ir change

update ir syntax

---

.github/workflows/run-examples.yml

the previous SystemTests string failed to match any tests, since it was missing the wildcard.

action: fix SystemTests and upload csv files

---

.github/workflows/run-examples.yml
.gitignore
src/test/scala/SystemTests.scala

example: https://github.com/UQ-PAC/BASIL/actions/runs/9884154629/attempts/1#summary-27300079028

add markdown output for github actions display

---

src/main/scala/analysis/data_structure_analysis/Graph.scala
src/main/scala/analysis/data_structure_analysis/LocalPhase.scala
src/main/scala/util/RunUtils.scala

Fixes bugs introduced in my recent merge and by 65c672a20b235bd51e3bd6e3e4e59d8c0b424227 so the DSA should produce correct dot files

DSA Dot Output fix

---

build.sbt
build.sc

Changelog:
- https://github.com/scala/scala3/releases/tag/3.3.4
- https://github.com/scala/scala3/releases/tag/3.3.3
- https://github.com/scala/scala3/releases/tag/3.3.2

Bump scala version to 3.3.4 - latest lts

---

src/main/scala/Main.scala
src/main/scala/analysis/InterLiveVarsAnalysis.scala
src/main/scala/ir/IRCursor.scala
src/main/scala/ir/Program.scala
src/main/scala/ir/Statement.scala
src/main/scala/ir/eval/SimplifyExpr.scala
src/main/scala/ir/transforms/DynamicSingleAssignment.scala
src/main/scala/ir/transforms/ProcedureParameters.scala
src/main/scala/ir/transforms/ReplaceReturn.scala
src/main/scala/ir/transforms/Simp.scala
src/main/scala/translating/IRExpToSMT2.scala
src/main/scala/translating/PrettyPrinter.scala
src/main/scala/util/Logging.scala
src/main/scala/util/RunUtils.scala
src/test/scala/SATTest.scala
src/test/scala/SystemTests.scala

Fixes to procedure parameter inference

Simplify fixes

---

src/main/scala/analysis/InterLiveVarsAnalysis.scala
src/main/scala/ir/Expr.scala
src/main/scala/ir/Program.scala
src/main/scala/ir/eval/SimplifyExpr.scala
src/main/scala/ir/transforms/ProcedureParameters.scala
src/main/scala/ir/transforms/ReplaceReturn.scala
src/main/scala/ir/transforms/Simp.scala
src/main/scala/util/RunUtils.scala

Contains small improvements to simplification and prototype implementation of copyprop through memory (curently disabeld).

WIP Memory copyprop

---

src/main/scala/analysis/Domains.scala
src/main/scala/analysis/Lattice.scala
src/main/scala/analysis/LatticeCollections.scala

Includes a special set and map representing terms in an abstract powerset lattice or map lattice.

Lattice sets and maps

---

src/main/scala/ir/dsl/DSL.scala
src/main/scala/ir/dsl/IRToDSL.scala
src/test/scala/ir/IRTest.scala
src/test/scala/ir/IRToDSLTest.scala
src/test/scala/ir/IRToDSLTestData.scala

still to do: 
- its only not supporting indices on formal parameters, which should never have an ssa index anyway

cloning: preserve labels and addresses

---

src/main/scala/translating/GTIRBLoader.scala

Handles the cvt_bits_uint and cvt_bits_sint operations produced by the ASLp lifter that convert bitvectors to integers. cvt_bits_uint is only encountered in floating point operations at the moment. This is handled by just keeping the argument as a bitvector as the conversion does not matter to BASIL's perspective currently. 
This will fix the errors for the correct/floatingpoint tests.

Handle cvt_bits_uint and cvt_bits_sint

---

src/main/scala/analysis/data_structure_analysis/SymbolicValueAnalysis.scala

Recognize calls to Calloc and create a Heap region per call

SVA handles calls to calloc

---

src/main/scala/analysis/data_structure_analysis/SymbolicValueAnalysis.scala

speed up SVA by replacing groupMapReduce with mapMerge

efficient map merge

---

src/main/scala/Main.scala
src/main/scala/boogie/BExpr.scala
src/main/scala/boogie/BProgram.scala
src/main/scala/boogie/FunctionOps.scala
src/main/scala/ir/Expr.scala
src/main/scala/ir/IRCursor.scala
src/main/scala/ir/IRType.scala
src/main/scala/ir/Program.scala
src/main/scala/ir/cilvisitor/CILVisitor.scala
src/main/scala/ir/dsl/StatementToScala.scala
src/main/scala/ir/eval/ExprEval.scala
src/main/scala/ir/transforms/ProcedureParameters.scala
src/main/scala/translating/IRExpToSMT2.scala
src/main/scala/translating/IRToBoogie.scala
src/main/scala/translating/IRToBoogieNoVC.scala
src/main/scala/util/BASILConfig.scala
src/main/scala/util/RunUtils.scala
src/main/scala/util/boogie/Boogie.scala
src/test/scala/ir/IRTest.scala
src/test/scala/test_util/BASILTest.scala

- adds quantifiers and Old() to IR
- adds direct translation of basil IR to boogie

Direct translation of BASIL IR to boogie and add quantifier expressions

---

src/main/scala/Main.scala

this changes `--help` argument to exit the program, instead of continuing to run Basil with the remainder of the arguments.
i found this surprising
```bash
$ basil --load-directory-gtirb src/test/correct/secret_write/clang/ --help
BASIL
--load-directory-bap <str>      Load relf, adt, and bir from directory (and spec from parent
directory)
--load-directory-gtirb <str>    Load relf and gts from directory (and spec from parent directory)
-i --input <str>                BAP .adt file or GTIRB/ASLi .gts file
-r --relf <str>                 Name of the file containing the output of 'readelf -s -r -W'.
-s --spec <str>                 BASIL specification file.
-o --output <str>               Boogie output destination file.
--boogie-use-lambda-stores      Use lambda representation of store …
```

make --help exit after printing help message

---

src/main/scala/cfg_visualiser/DotTools.scala
src/main/scala/util/RunUtils.scala

Should hopefully prevent #422 from being an issue

Consistently use flags for outputting .dot and .il files

---

src/main/scala/translating/BAPToIR.scala

Prevent Blocks from being added to BAP atomics handling queue repeatedly

---

docs/src/development/readme.md

pls forgive the trailing whitespace changes

docs: use `./mill fmt` instead of old scalafmt

---

src/main/scala/analysis/data_structure_analysis/Utility.scala

unify corresponding nodes during cloning 

---

src/main/scala/ir/transforms/ProcedureParameters.scala

fix spec param rewriting

---

src/main/scala/translating/IRToBoogieNoVC.scala
src/main/scala/util/RunUtils.scala

Fixes https://github.com/UQ-PAC/BASIL/issues/547 but makes no attempt to do something meaningful if the spec contains undefined gammas.

add spec to --noif output

---

src/main/scala/translating/ReadELFLoader.scala

fixes https://github.com/UQ-PAC/BASIL/issues/563

fix: add INTERNAL elf visibility mode
