UQ-PAC/BASIL

src/main/java/translating/FlowGraph.java, src/main/java/translating/FlowGraphVisualiser.java, src/main/scala/translating/BoogieTranslator.scala, src/main/scala/vcgen/VCGen.scala
- Functions in flow graphs now contain a list of all their blocks
- moved functionality for getting all blocks / all lines in a function to the Function class
- refactored BoogieTranslator to utilise setters instead of modifying lists returned by these aforementioned methods ^
=> Major edits on flowgraph, some refactoring on translator

src/main/scala/analysis/Analysis.scala, src/main/scala/analysis/Cfg.scala, src/main/scala/astnodes/Expr.scala, src/main/scala/astnodes/Program.scala, src/main/scala/astnodes/Statement.scala, src/main/scala/translating/BoogieTranslator.scala, src/main/scala/util/RunUtils.scala
Changed the ast to be mutable (ie. by changing the case classes to regular classes). This resulted in the need to manually define copy methods. Also, changes to the match function as classes moved from using the unapply method provided by the case class to matching the class type manually (instance matching) and extracting the class variables.
=> Changed the ast to be mutable

build.sbt, readme.md, src/main/scala/Main.scala, src/test/scala/SystemTests.scala
Uses lihaoyi/mainargs to parse CLI args in stead of ad-hoc logic. Arguments are no longer positional and all require flags. This is my preference for clarity and simplicity, but isn't compatible with the previous format. 
```
BASIL
-a --adt <str>     BAP ADT file name.
-r --relf <str>    Output of 'readelf -s -r -W'.
-s --spec <str>    BASIL specification file.
-o --output <str>  Boogie output destination file.
-v --verbose       Show extra debugging logs.
--analyse          Run static analysis pass.
--interpret        Run BASIL IL interpreter.
-h --help          Show this help message.
```
=> refactor cli arg parsing

src/main/scala/Main.scala, src/main/scala/ir/Expr.scala, src/main/scala/ir/Program.scala, src/main/scala/translating/ILtoIL.scala, src/main/scala/util/RunUtils.scala, src/test/scala/MemoryRegionAnalysisMiscTest.scala
For debugging and regression detection it is good to have a text output of the intermediate language, this is a basic implementation of that, aiming to make it look close to the internal datastructures with some explanatory syntax.
E.g. for secret_write: 
```
Procedure("1980:main", in(Parameter(Register(R0, bv64)), Parameter(Register(R1, bv64))), out(Parameter(Register(R1, bv64)), Parameter(Register(R0, bv64))), blocks(
Block("1980:lmain",
statements(
LocalAssign(LocalVar(#5, bv64) := Expr(BinaryExpr(Expr(Register(R31, bv64)), Expr(18446744073709551584bv64))))
MemoryAssign(MemoryStore(Memory(Memory(mem, 64, 8))[Expr(LocalVar(#5, bv64))] := Expr(Register(R29, bv64))))
MemoryAssign(MemoryStore(Memory(Memory(mem, 64, 8))[Expr(BinaryExpr(Expr(LocalVar(#5, bv64)), Expr(8bv64)))] := …
```
=> Serialise IL

src/main/scala/analysis/VSA.scala
Adds local assign expressions that can be evaluated to literals to the VSA 
Functionally this is just merging the constant propagation results into the vsa
Before commit 93d99378cd96185c71f677f72a7bc3dce3cc6a20 the VSA tracked values of registers, but unclear if this was broken in a merge later or something else.
=> Evaluate literal expressions in vsa

src/test/correct/basic_arrays_write/clang_pic/basic_arrays_write.expected, src/test/correct/basic_arrays_write/gcc_pic/basic_arrays_write.expected, src/test/correct/basic_assign_assign/clang_pic/basic_assign_assign.expected, src/test/correct/basic_assign_assign/gcc_pic/basic_assign_assign.expected, src/test/correct/basic_assign_increment/clang_pic/basic_assign_increment.expected, src/test/correct/basic_assign_increment/gcc_pic/basic_assign_increment.expected, src/test/correct/basic_function_call_caller/clang/basic_function_call_caller.expected, src/test/correct/basic_function_call_caller/clang_no_plt_no_pic/basic_function_call_caller.expected, src/test/correct/basic_function_call_caller/gcc/basic_function_call_caller.expected, src/test/correct/basic_function_call_caller/gcc_no_plt_no_pic/basic_function_call_caller.expected, src/test/correct/basic_function_call_reader/clang_pic/basic_function_call_reader.expected, src/test/correct/basic_function_call_reader/gcc_pic/basic_function_call_reader.expected, src/test/correct/basic_lock_read/clang_pic/basic_lock_read.expected, src/test/correct/basic_lock_security_read/clang_pic/basic_lock_security_read.expected, src/test/correct/basic_lock_security_read/gcc_pic/basic_lock_security_read.expected, src/test/correct/basic_lock_unlock/clang_pic/basic_lock_unlock.expected, src/test/correct/basic_lock_unlock/gcc_pic/basic_lock_unlock.expected, src/test/correct/basic_loop_assign/clang_pic/basic_loop_assign.expected, src/test/correct/basic_loop_assign/gcc_pic/basic_loop_assign.expected, src/test/correct/basic_sec_policy_read/clang_pic/basic_sec_policy_read.expected, src/test/correct/basic_sec_policy_read/gcc_pic/basic_sec_policy_read.expected, src/test/correct/basicassign_gamma0/clang_pic/basicassign_gamma0.expected, src/test/correct/basicassign_gamma0/gcc_pic/basicassign_gamma0.expected, src/test/correct/no_interference_update_x/clang_pic/no_interference_update_x.expected, src/test/correct/no_interference_update_x/gcc_pic/no_interference_update_x.expected, src/test/correct/no_interference_update_y/clang_pic/no_interference_update_y.expected, src/test/correct/no_interference_update_y/gcc_pic/no_interference_update_y.expected, src/test/correct/using_gamma_conditional/clang_pic/using_gamma_conditional.expected, src/test/correct/using_gamma_conditional/gcc_pic/using_gamma_conditional.expected, src/test/scala/SystemTests.scala
Addressing #77 a little bit. With these time limits the tests still take far too long on the latest Boogie (~15 minutes on Boogie 3.0.4 vs. ~4 minutes on 2.16.0 on my machine) but at least they're runnable.
=> Time limits for SystemTests

examples/basic_arrays_read/basic_arrays_read.spec, examples/basic_arrays_write/basic_arrays_write.spec
#87
These specs had been updated in the tests folder but not the examples folder when the implementation changed. A further cleanup there will need to happen at some point, but this will prevent any confusion with this example for now.
=> Fix outdated example specs

scripts/format_adt.py
This makes it easier to inspect .adt files manually without the burden of fully parsing them.
The formatter works by exploiting the almost-Python syntax of the ADT. It tweaks it into valid Python, then parses and formats it using Python's ast.literal_eval and pprint.pprint modules. After this, it reverses the transformation to produce something very much like BAP.
Is this something you would like to have?
Example output from the formatted secret_write.adt:
```python
Program(
Tid(1_696, "%000006a0"),
Attrs([]),
Subs(
[Sub(
Tid(1_646, "@__cxa_finalize"),
Attrs(
[Attr("c.proto", "signed (*)(void)"),
Attr("address", "0x5D0"),
Attr("stub", "()")]),
"__cxa_finalize",
Args(
[Arg(
Tid(1_697, "%000006a1"),
Attrs(
[Attr("c.layout", "[signed : 32]"),
Attr("c.data", "Top:u32"),
Attr("c.type", …
```
=> add .adt pretty-printer in format_adt.py

scripts/format_adt.py
This gives a 10x speedup for approximately the same result.
cntlm.adt now formats in 10 seconds (2s with pypy) using marginal memory.
This also fixes a mis-formatting of memory bytes.
=> format_adt: refactor to manually-written formatter

src/main/scala/analysis/Analysis.scala, src/main/scala/analysis/BitVectorEval.scala, src/main/scala/analysis/Cfg.scala, src/main/scala/analysis/Dependencies.scala, src/main/scala/analysis/Lattice.scala, src/main/scala/analysis/MemoryModelMap.scala, src/main/scala/analysis/SteensgaardAnalysis.scala, src/main/scala/analysis/UtilMethods.scala, src/main/scala/analysis/VSA.scala, src/main/scala/analysis/solvers/FixPointSolver.scala, src/main/scala/analysis/solvers/MonotonicSolver.scala, src/main/scala/ir/Interpreter.scala, src/main/scala/util/RunUtils.scala, src/test/scala/ir/InterpreterTests.scala
This is a number of changes to the analysis code.
One of the main changes is making all the types in the analysis explicitly declared instead of relying on a maze of .Elements with convoluted inheritance patterns. I personally find this makes the code easier to follow. I am curious for feedback here from @ailrst and @yousifpatti  - is this an improvement? 
Other changes here:
- Consolidates and cleans up parts of the analysis, to reduce the convoluted inheritance patterns
- Enables procedure inlining in the CFG so that there are actually interprocedural edges in the CFG
- Makes interprocedural analyses actually use the interprocedural edges (before they were in practice not meaningly different from the intraprocedural analyses) but this still doesn't seem to be completely working …
=> Analysis Cleanup and Explicit Types

src/main/scala/ir/Expr.scala, src/main/scala/ir/Program.scala, src/main/scala/ir/Visitor.scala, src/main/scala/util/RunUtils.scala, src/test/scala/ir/InterpreterTests.scala
Makes all Exprs immutable case classes.
I plan to add more Visitors to make this easier to work with, and move the rest of Procedure.stackIdentification.visitBlock to the new StackSubstituter Visitor too.
=> Make Exprs Immutable

build.sc, src/main/scala/ir/IRCursor.scala, src/main/scala/util/Logging.scala, src/main/scala/util/RunUtils.scala, src/test/analysis/livevars/dump/livevar_analysis_results, src/test/analysis/livevars/dump/param_analysis_results, src/test/analysis/params/dump/livevar_analysis_results, src/test/analysis/params/dump/param_analysis_results, src/test/scala/MemoryRegionAnalysisMiscTest.scala, src/test/scala/ir/InterpreterTests.scala
Refactors runutils to more cleanly separate the loading, analysis, and translation phases. 
We now have 3 objects, `Loading` `IRTransform` `StaticAnalysis` which contain only methods and no state, and 3 case classes, `IRContext`, `StaticAnalysisContext` and `BasilResult` which hold the results from each phase. 
We might still want to break up the `StaticAnalysis.analyze` further in the future.
=> Runutils cleanup

src/test/scala/LiveVarsAnalysisTests.scala, src/test/scala/ParamAnalaysisTests.scala, src/test/scala/test_util/TestUtil.scala
Addresses #189 and #179 review comments about tests using inputs from test folder instead of examples folder
=> Tests use "./src/test/correct/" instead of examples

src/main/scala/boogie/BExpr.scala, src/main/scala/translating/SemanticsLoader.scala
Supports the 'replicate_bits' operation from ASLi. This does not show up much (due to deliberate attempts to avoid producing it?) but is produced for instructions like `ld1r` and it is trivial to support so we may as well.
=> replicate_bits support

src/main/scala/util/RunUtils.scala
This adds an assertion before an indirect call resolved to multiple possible targets that asserts that the indirect call target variable can only contain one of the values determined by the static analysis.
=> Assertion to check underapproximation when resolving indirect calls

src/main/antlr4/ReadELF.g4, src/main/scala/translating/ReadELFLoader.scala, src/main/scala/translating/SemanticsLoader.scala, src/main/scala/util/RunUtils.scala
- handle unsupported opcodes from https://github.com/UQ-PAC/gtirb-semantics/pull/22
- disambiguate functions with local binding (c `static`) which have the same name but different addresses in the boogie output
- handle relf files with empty relocation table
- some missing relf enum values
=> frontend fixes

src/main/scala/analysis/MemoryModelMap.scala
Updating and extending the MRA docs with Yousif before he leaves.
=> Add more docs about MRA data structures.

src/main/scala/ir/transforms/AbsInt.scala
Allows the initial states for blocks without predecessors to be specified using init in abstract domain
=> Simplification pass initial state

src/main/scala/Main.scala, src/main/scala/analysis/IrreducibleLoops.scala, src/main/scala/ir/Program.scala, src/main/scala/ir/transforms/AbsInt.scala, src/main/scala/ir/transforms/Simp.scala, src/main/scala/translating/PrettyPrinter.scala, src/main/scala/util/Logging.scala, src/main/scala/util/RunUtils.scala
- add loop information to the IR so you can easily implement widening heuristic in the AbstractDomain.join function without proper solver support
```scala
class Block {
var inLoop: Set[Loop]
def isLoopHeader () : Bool
def isLoopParticipant () : Bool
}
```
- Add simple interprocedural solver which takes a fixed-point over the call graph (very naive inefficient implementation but seems OK for definitely-returns analysis in cntlm-noduk). 
This applies an interprocedural analysis to each procedure, abstracts the results to a summary for the procedure-level, and takes this to a fixed point.
To use this define a local analysis `AbstractDomain[LocalDomain]`, and a summary generator:
```scala
trait ProcedureSummaryGenerator[L, LocalDomain] extends GenericAbstractDomain[Procedure, Procedure, L] { …
```
=> Add block info, interproc solver, analysis prettyprinter

src/main/scala/translating/GTIRBLoader.scala, src/main/scala/translating/GTIRBToIR.scala, src/main/scala/util/RunUtils.scala
Updates frontend to support the format in  https://github.com/UQ-PAC/gtirb-semantics/pull/22
Test code: [gate_server_example.tar.gz](https://github.com/user-attachments/files/18194266/gate_server_example.tar.gz)
Also adds a case to loading `cvt_bool_bv` that wasn't covered previously.
=> Support new lifter unsupported opcode format

src/main/scala/cfg_visualiser/DotTools.scala, src/main/scala/ir/cilvisitor/CILVisitor.scala, src/main/scala/ir/eval/SimplifyExpr.scala, src/main/scala/translating/GTIRBLoader.scala, src/main/scala/translating/GTIRBToIR.scala, src/main/scala/util/RunUtils.scala, src/test/scala/ir/CILVisitorTest.scala
Some fixes to get cntlm lifted with the offline lifter to go through the gtirb frontend
- relax the expectations of the gtirb loader a bit so it doesn't immediately crash on bad rASL and detached blocks
- more assertions in simplifier as I keep adding them when debugging
- fix to repeat bits in cil visitor
=> fixes from cntlm with offline lifter

src/main/scala/Main.scala, src/main/scala/analysis/data_structure_analysis/Constraints.scala, src/main/scala/analysis/data_structure_analysis/SymbolicValueAnalysis.scala, src/main/scala/ir/Program.scala, src/main/scala/util/BASILConfig.scala, src/main/scala/util/Logging.scala, src/main/scala/util/RunUtils.scala, src/test/scala/SVATest.scala
Implements DSA pre-pass (Symbolic Value Analysis and Constraint generation)
Adds flag interface for specifying DSA type
`--dsa (none|norm|set|field|all)`
currently all options are equivalent to none which computes constraints but doesn't perform DS analysis
=> constraint generation

src/main/scala/ir/Expr.scala, src/main/scala/ir/dsl/DSL.scala, src/main/scala/util/functional/State.scala, src/test/scala/ir/CILVisitorTest.scala, src/test/scala/ir/IRTest.scala
Example
```scala
val p = prog(
proc("p1", Seq(("R0_in" -> BitVecType(64))), Seq(("R0_out", BitVecType(64))),
block("b1",
ret("R0_out" -> LocalVar("R0_in", BitVecType(64)))
)
),
proc("main", Seq(), Seq(("R0_out") -> BitVecType(64)),
block("l_main",
indirectCall(R1), goto("returntarget")
),
block("block2",
directCall(Seq(("R0_out" -> R0)), "p1", "R0_in" -> BitVecLiteral(150, 64)), goto("returntarget")
),
block("returntarget",
ret("R0_out" -> BitVecLiteral(1, 64))
)
),
)
```
=> Support parameters IR DSL

src/main/scala/analysis/InterLiveVarsAnalysis.scala, src/main/scala/analysis/LatticeCollections.scala, src/main/scala/cfg_visualiser/DotTools.scala, src/main/scala/ir/IRCursor.scala, src/main/scala/ir/invariant/AllVarsIndex.scala, src/main/scala/ir/transforms/AbsInt.scala, src/main/scala/ir/transforms/ProcedureParameters.scala, src/main/scala/ir/transforms/ReplaceReturn.scala, src/main/scala/ir/transforms/Simp.scala, src/main/scala/translating/GTIRBLoader.scala, src/main/scala/translating/GTIRBToIR.scala, src/main/scala/util/RunUtils.scala
We were missing in and out parameters due to the inter-procedural effects of introducing the parameters, e.g. out-parameters that are required due to being modified in the procedure and live after, but which were not known to be live by the initial liveness analysis (i.e. a use is introduced by adding the out-parameter to the return statement).
(image below shows the before and after the DSA pass for a buggy example; R3 has not been made an inparam so `lf_goto_l00..30f` on the RHS uses the uninitialised `R3` variable.) This pr adds r3 as an in-param. Without [5e2b215](https://github.com/UQ-PAC/BASIL/pull/314/commits/5e2b2150fddb5923991374f4f590ed461d0c7308)it will remove r3 as an out-param.
fixed: 
I added an invariant check to make sure the dynamic single assignment doesn't produce an …
=> Improve in-param detection completeness

src/main/scala/analysis/ConstantPropagation.scala, src/main/scala/analysis/Lattice.scala, src/main/scala/ir/Expr.scala
idk why they weren't sealed, but it everything seems to compile with this change so it's probably fine
new non-exhaustive warnings:
```scala
[warn] -- [E029] Pattern Match Exhaustivity Warning: /home/rina/progs/basil/src/main/scala/analysis/ConstantPropagation.scala:21:12 
[warn] 21 |        bin.op match {
[warn]    |        ^^^^^^
[warn]    |match may not be exhaustive.
[warn]    |
[warn]    |It would fail on pattern case: BoolEQ, BoolNEQ, BoolAND, BoolOR, BoolIMPLIES, BoolEQUIV
[warn]    |(More unmatched cases are elided)
[warn]    |
[warn]    | longer explanation available when compiling with `-explain`
[warn] -- [E029] Pattern Match Exhaustivity Warning: /home/rina/progs/basil/src/main/scala/analysis/ConstantPropagation.scala:44:11 
[warn] 44 |        un.op match {
[warn]    | …
```
=> expr: make BinOp and UnOp sealed

src/main/scala/ir/Expr.scala, src/main/scala/ir/Statement.scala, src/main/scala/translating/GTIRBToIR.scala
this changes the return type of irrefutable unapply methods to be Some[...] instead of Option[...], aiding the compiler's deduction of pattern-match exhaustivity.
this avoids confusing warnings where there is a case
```scala
case LocalVar(_, _, _) => ...
```
but the compiler still says
it would fail on pattern case: _: ir.LocalVar
\- presumably accounting for the situation where the unapply method returns None.
with this change, we are also able to remove one "unreachable code" assertion in GTIRBToIR.scala, as the compiler correctly deduces it is unreachable.
in fact, if you remove that explicit unreachable case without applying this PR, the scala compiler suggests this change with -explain:
```scala
[warn] -- [E029] Pattern Match Exhaustivity Warning: …
```
=> Return Some[] from irrefutable unapply methods

.scalafmt.conf
this changes the docstring formatting mode to "keep", which tells scalafmt to make no modifications to docstring formatting
scalafmt is, by default, very enthusiastic about formatting docstrings. it will replace syntax like
/**
* aaa
* ---
*/
with the asterisks moved and, worse, the subheading line merged into the preceding line,
/**
* aaa ---
*/
i don't believe the docstrings need to be subjected to this level of re-formatting, and it breaks markdown formatting (despite markdown being [preferred] by scaladoc). slight differences in otherwise well-formatted docstrings are fine. if a docstring is truly very bad, it should be pointed out in code review.
[preferred]: https://docs.scala-lang.org/scala3/guides/scaladoc/docstrings.html#markup
=> formatting: disable formatting of docstrings

src/main/scala/ir/transforms/Simp.scala, src/main/scala/util/RunUtils.scala
The experimental copyprop through memory is incorrect because of cases like: https://github.com/UQ-PAC/BASIL/issues/329
Its making too strong an assumption of ordering of loads and stores which we only have in the case of variables because of the DSA. I should delete this code eventually, but I'm leaving it for now as it would probably be possible to hack in this assumption by also requiring the propagated store to dominate the load. It would make more sense to to memory promotion to variables and apply regular copyprop however. 
The case this fixes is here: It should not propagate load_27 to the right branch where it isn't reachable.
=> simplifier: disable memory copyprop

src/main/scala/ir/dsl/DSL.scala, src/main/scala/ir/dsl/IRToDSL.scala
also,
- remove CallStatement because it was just Call, and
- replace leftover use of ControlStatement in function names with CallStatement.
=> IRToDSL: touch up the NonCallStatement with comment

scripts/liftmake.sh
This is a small script to compile and lift examples by wrapping make. It is compatible with the reproducible build environment by pulling compiler and lifter binary paths from environment variables.
=> Liftmake script

src/main/scala/ir/IRCursor.scala, src/test/scala/InterpretTestConstProp.scala, src/test/scala/util/TestValueAnalysisWithInterpreter.scala
This factors out the `InterpretConstProp` test into a more reasonable separate generic test for checking value analyses against the interpreter. 
You have to provide 
1. An analysis result `block -> variable -> absval`
2. A function `valueInAbstractVal: abstract:absval -> concrete:expr -> expr` which encodes the soundness check as a basil IR expression that evaluates to true when the `concrete` is an element of `abstract`. 
Its a bit iffy on choosing which variables to generate assertions for, if you test uninitialised variables it will crash the interpreter, but its fairly normal for uninitialised variables to appear in abstract domains.
=> create more generic interpreter test for value analysis

src/main/scala/ir/Program.scala, src/main/scala/ir/cilvisitor/CILVisitor.scala, src/main/scala/ir/transforms/Inline.scala, src/main/scala/ir/transforms/InlinePLTLaunchpad.scala, src/main/scala/util/RunUtils.scala
This adds a function to perform procedure inlining that preserves DSA form. It adds a pass  under --simplify that inlines the plt launchpads from gtirb with a very basic heuristic. 
Its tested inasfar as `--validate-simplfy` succeeds on running cntlm, so it preserves DSA form. It needs a stronger test to make sure dataflow isn't being lost though. 
[example diff](https://www.jstoolset.com/diff/2a2167f417ddc158)
=> Procedure call inlining

src/test/scala/IndirectCallTests.scala
Partially fixes #358
Does not fix the issue with jumptable3/clang:GTIRB and switch2/clang:GTIRB failing due to the DSA producing expressions with mismatched sizes
=> Fixes issue with IndirectCallTests expecting incorrect names for procedures

src/main/scala/analysis/data_structure_analysis/Utility.scala, src/main/scala/ir/eval/SimplifyExpr.scala, src/test/scala/IndirectCallTests.scala
Addresses the low hanging fruit issues with `IndirectCallTests`: fixes https://github.com/UQ-PAC/BASIL/issues/358
- Reimplement `unwrapPaddingAndSlicing` using the expression simplifier, this works fine for most genuine pointer arithmetic that appears in the simple tests, but I'm unsure how to fully test that it doesn't produce any precision regressions. 
- Fix the procedure name testing in IndirectCallTests
This goes from 28 failing to 11 failing in `IndirectCallTests`
The remaining failures are, which are expected to fail due to missing features. 
```
- indirect_call_outparam/clang:BAP *** FAILED ***
Resolving IndirectCall main: %0000037a -> Procedures[seven] failed:
call not resolved to correct target: %0000037a: IndirectCall(Register(R8, bv64))
Expected verification success, but got …
```
=> IndirectCallTest fixes

src/main/scala/ir/eval/InterpretTrace.scala, src/main/scala/ir/eval/Interpreter.scala, src/main/scala/util/Logging.scala, src/main/scala/util/PerformanceTimer.scala, src/main/scala/util/functional/State.scala, src/test/scala/DifferentialAnalysisTest.scala, src/test/scala/ir/InterpreterTests.scala
This was concatenating to the end of a list making the tracing interpreter quadratic (ty @katrinafyi for spotting this). 
This makes the runtime go from ~30s to 4s for the examples here https://github.com/UQ-PAC/BASIL/pull/322.
Commenting out the disabled `Logger.debug` calls seems to save ~1% of runtime, since these aren't actually evaluated I can only assume its the overhead of 2-3 method calls and branching.
=> Interpreter: use Vector for trace instead of List

src/main/scala/ir/transforms/ProcedureParameters.scala
Fixes https://github.com/UQ-PAC/BASIL/issues/363
=> parameter form: Keep Old() when rewriting spec to support memload/store

src/main/scala/ir/eval/InterpretBasilIR.scala, src/main/scala/ir/eval/Interpreter.scala, src/main/scala/translating/IRExpToSMT2.scala, src/main/scala/util/RunUtils.scala, src/main/scala/util/functional/State.scala, src/test/scala/ir/InterpreterTests.scala
This refactors the interpreter entrypoint around the function `callProcedure`, which returns a future which immediately evaluates the call to the procedure and returns its return values (if the procedure has out-parameters defined). The goal here is to make it easier to write tests such that you can simply write a procedure literal, and evaluate it, and assert the return value. 
This also lays the groundwork to cleanup the implementation of intrinsic functions. Currently we have intrinsics that expect to read/write global registers, so calls with formal parameters are stored to the expected global variables before the call, and read back after. This can be substantially cleaned up (and some indirection removed) by instead standardising intrinsics on the parameter form, and if the IR …
=> Interpreter: callProcedure with return values

build.sc, src/main/scala/ir/dsl/DSL.scala, src/main/scala/ir/dsl/IRToDSL.scala, src/main/scala/ir/transforms/Inline.scala
The .toArray method converts an iterable to an Array. However, this is a minimal Java-esque array and does not support any of Scala's interfaces. Where an interface like Iterable or Seq was needed, this would require a coercion from Array to ArraySeq, which the compiler warns about because it incurs an additional copy.
This fixes the deprecation warning by using converting directly to ArraySeq, avoiding the implicit coercion and unnecessary copy.
**Also,** enables -deprecation in the mill build config. This will show deprecation warnings in the CI job.
Under the umbrella of: https://github.com/UQ-PAC/BASIL/issues/339.
=> fix: deprecation warnings caused by .toArray

src/main/scala/ir/eval/InterpretBasilIR.scala, src/main/scala/ir/eval/InterpretRLimit.scala, src/main/scala/ir/eval/InterpretTrace.scala, src/main/scala/ir/eval/Interpreter.scala, src/test/scala/DifferentialAnalysisTest.scala, src/test/scala/ir/InterpreterTests.scala
Fixes DifferentialAnalysisTest
=> Fix interpreter entrypoint for other interpreters

src/main/scala/analysis/data_structure_analysis/DSA.scala, src/main/scala/analysis/data_structure_analysis/DataStructureAnalysis.scala, src/main/scala/analysis/data_structure_analysis/Graph.scala, src/main/scala/analysis/data_structure_analysis/IntervalDSA.scala, src/main/scala/analysis/data_structure_analysis/LocalPhase.scala, src/main/scala/analysis/data_structure_analysis/Utility.scala, src/main/scala/ir/transforms/Inline.scala, src/main/scala/util/Counter.scala, src/main/scala/util/ThreadUtils.scala
This change unifies all counter implementations in the codebase with a single class at util.Counter. The util.Counter implementation is specifically made thread-safe.
This is my leading hypothesis for the cause of https://github.com/UQ-PAC/BASIL/issues/370. This is not based on any evidence, but this kind of thing is likely to cause problems with concurrent code.
Also adds some helper functions to try and help debug concurrency problems. They did not help in this case but might in future.
=> utils: add a thread-safe Counter, and use it to replace all counters

src/main/scala/ir/Expr.scala, src/main/scala/ir/Program.scala, src/main/scala/ir/eval/SimplifyExpr.scala, src/main/scala/ir/transforms/Simp.scala, src/main/scala/util/CachedHashCode.scala
This implements two separate micro-optimisations to speed up the simplification pass, using cntlm-noduk as a benchmark and guided by profiling.
- First, we cache the hashCode() result of case classes the first time they are computed. Given the prevalence of hashmaps, this is a very frequent operation and hashCode of strings and bigints is slow (enough) that it matters.
- Second, we make some very minor changes to the simp CopyProp to reduce the number of hashmap searches needed.  This is again a hotspot and each individual `c(l)` performs a lookup of the hashmap.
I have benchmarked this against 72338dd25eb984bd8dcec83e773327e1fe0d0573 and we see a 36\% speedup on this cntlm-noduk example. (The size of this example might exaggerate the performance improvements.)
```python
Benchmark 1: java …
```
=> micro-optimisations: cached hashcode and reduce hashmap lookups

src/main/scala/Main.scala, src/main/scala/util/RunUtils.scala, src/main/scala/util/boogie/Boogie.scala, src/test/scala/IndirectCallTests.scala, src/test/scala/SystemTests.scala, src/test/scala/test_util/BASILTest.scala
This factors out the Boogie output parsing from system tests to share with the implementation of basil's `--verify` flag. 
This means we now have the output below:
```
$ mill run --load-directory-gtirb src/test/correct/initialisation/gcc --analyse --memory-regions mra --verify -o basil-out-2.bpl
...
[INFO]   [!] Translating to Boogie
[INFO]   Writing output
[INFO]   Running: boogie /useArrayAxioms basil-out-2.bpl /printVerifiedProceduresCount:0
basil-out-2.bpl(192,5): Error: a postcondition could not be proved on this return path
basil-out-2.bpl(124,3): Related location: this is the postcondition that could not be proved
Execution trace:
basil-out-2.bpl(137,3): main_1812__0__ulEp46faSbyYIP08N0ny3w
Boogie program verifier finished with 1 error
[INFO]   Boogie result: AssertionFailed …
```
=> Factor out Boogie tool output parsing

src/main/scala/analysis/Dominators.scala, src/test/scala/DominatorsTest.scala
This implements a simple function to compute dominators of a block. A dominator of a block `b` is a block `b'` such that every path from the entry (of a procedure) to `b` first passes through `b'`.
To determine whether two arbitrary blocks dominate each other, you should first compute the dominator tree. Then, pass this to `Dominator.dominates` to obtain a binary predicate on blocks.
This follows the algorithm in https://hdl.handle.net/1911/96345. Although this runs in quadratic time, the paper notes that it is simpler and empirically faster than asymptotically faster algorithms for realistic sizes of programs.
=> add: dominator tree computation

.github/workflows/run-examples.yml, src/main/scala/analysis/MemoryRegionAnalysis.scala, src/main/scala/ir/Program.scala, src/main/scala/ir/eval/InterpretBasilIR.scala, src/main/scala/ir/eval/InterpretTrace.scala, src/main/scala/ir/eval/Interpreter.scala, src/main/scala/ir/transforms/LinuxAssertFail.scala, src/main/scala/ir/transforms/ProcedureParameters.scala, src/main/scala/ir/transforms/ReplaceReturn.scala, src/main/scala/ir/transforms/Simp.scala, src/main/scala/util/RingTrace.scala, src/main/scala/util/RunUtils.scala, src/main/scala/util/functional/State.scala, src/test/scala/DifferentialAnalysisTest.scala
A set of changes to make the differential testing of the simplification pass work. 
- fix the handling of intrinsics for the new callProcedure structure (indirect calls dispatching to intrinsics is likely still broken)
- enable simplify pass in the DifferentialAnalysisTest, disable the other test as `--analyse` doesn't make any transforms to test (aside from indirect calls which aren't in this set of examples here, and the interpreter doesn't support memory regions yet. The interpreter also tends to fall over on the indirect call examples, partly due to stack protection).
- add a transform pass to `--simplify` to pull the assume guards back in front of the phi/copies inserted on branch edges, after DSA. This substitutes the copies into the assume statement. When the assume sits on a, DSA …
=> Simplify cleanup branches guards

src/main/scala/ir/Program.scala, src/main/scala/ir/invariant/ProcEntryNoIncoming.scala, src/main/scala/ir/transforms/DynamicSingleAssignment.scala, src/main/scala/ir/transforms/Simp.scala, src/main/scala/util/RunUtils.scala, src/test/scala/SingleAssignmentTest.scala
Addresses https://github.com/UQ-PAC/BASIL/issues/378
The offending function was `errorFn_1848`, which was a single empty block jumping to itself, after param anslysis we got the following:
```
proc errorFn_1848(R0_in:bv64, R10_in:bv64, R11_in:bv64, R12_in:bv64, R13_in:bv64, R14_in:bv64, R15_in:bv64, R16_in:bv64, R17_in:bv64, R18_in:bv64, R1_in:bv64, R29_in:bv64, R2_in:bv64, R30_in:bv64, R31_in:bv64, R3_in:bv64, R4_in:bv64, R5_in:bv64, R6_in:bv64, R7_in:bv64, R8_in:bv64, R9_in:bv64) -> ()
{
name = "errorFn";
address = 0x738;
entry_block = "errorFn_1848__0__b8tsihT4Q6a_SWPo4w8HoA";
blocks = [
block errorFn_1848__0__b8tsihT4Q6a_SWPo4w8HoA {address = 0x738} [
var R0: bv64 := R0_in:bv64;
var R10: bv64 := R10_in:bv64;
var R11: bv64 := R11_in:bv64;
var R12: bv64 := R12_in:bv64;
var R13: bv64 := …
```
=> Fix dsa assertion

.github/workflows/check-test-tagging.sh
the previous regex would fail to find the test case definition if it appeared on multiple lines, e.g.:
```scala
@test_util.tags.UnitTest
class BitVectorAnalysisTests
extends AnyFunSuite {
```
this led to false alarms in the ci runs.
also improves and refactors the script to make it a bit more robust, with clearer error messages and less silent failures
with this pr, i avoid having to rewrite the script. but maybe the time will come soon...
this has been tested to fix the ci failure in https://github.com/UQ-PAC/BASIL/actions/runs/14326080264/job/40151684127?pr=335
=> ci: fix word regex in check-test-tagging

.github/workflows/check-test-tagging.sh, src/main/scala/util/Logging.scala, src/test/scala/BitVectorAnalysisTests.scala, src/test/scala/DataStructureAnalysisTest.scala, src/test/scala/DifferentialAnalysisTest.scala, src/test/scala/IndirectCallTests.scala, src/test/scala/InterpretTestConstProp.scala, src/test/scala/IntervalDSATest.scala, src/test/scala/IrreducibleLoop.scala, src/test/scala/LiveVarsAnalysisTests.scala, src/test/scala/ParamAnalysisTests.scala, src/test/scala/PointsToTest.scala, src/test/scala/SATTest.scala, src/test/scala/SVATest.scala, src/test/scala/SystemTests.scala, src/test/scala/TaintAnalysisTests.scala, src/test/scala/ir/CILVisitorTest.scala, src/test/scala/ir/IRTest.scala, src/test/scala/ir/IRToDSLTest.scala, src/test/scala/ir/InterpreterTests.scala, src/test/scala/ir/SingleCallInvariant.scala, src/test/scala/ir/ToScalaTest.scala, src/test/scala/test_util/CaptureOutput.scala, src/test/scala/test_util/FunctionOutputStream.java, src/test/scala/test_util/ThreadOutputStream.java, src/test/scala/util/ScalatestPrettierTest.scala, src/test/scala/util/StateMonad.scala, src/test/scala/util/StringUtilsTests.scala, src/test/scala/util/intrusive_list/IntrusiveListPublicInterfaceTest.scala, src/test/scala/util/intrusive_list/IntrusiveListTest.scala
Since test suits have been parallelised, there is this problem where logging stdout/stderr is printed to console and it is not clear which test suite an output message relates to. This is because the standard streams are shared by all threads.
This change will redirect stdout/err within test cases to info() messages.
This helps organise the test output, especially when running in
parallel. With this change, stdout/stderr are redirected through
scalatest's info() method, allowing the output to be associated and
printed with the name of the test case.
The output now looks something like this. You can see the stdout/err lines are prefixed with `+` and indented underneath the test case name.
This change does have some disadvantages.
- Both stdout/stderr are redirected to info() with no …
=> tests: redirect test stdout/err to info() messages 

src/main/scala/analysis/data_structure_analysis/Graph.scala
fixes issue with assume variables not being included as formals in DataStructureAnalysis 
#390
=> include variables in assume when initialising varToCell

src/main/scala/analysis/data_structure_analysis/DSA.scala, src/main/scala/analysis/data_structure_analysis/IntervalDSA.scala, src/main/scala/analysis/data_structure_analysis/SymbolicValueAnalysis.scala, src/main/scala/ir/Statement.scala, src/main/scala/ir/Visitor.scala, src/main/scala/ir/cilvisitor/CILVisitor.scala, src/main/scala/ir/dsl/DSL.scala, src/main/scala/ir/dsl/StatementToScala.scala, src/main/scala/ir/transforms/MemoryTransform.scala, src/main/scala/ir/transforms/Simp.scala, src/main/scala/translating/IRExpToSMT2.scala, src/main/scala/util/RunUtils.scala, src/test/scala/IntervalDSATest.scala, src/test/scala/MemoryTransfromTests.scala, src/test/scala/SystemTests.scala, src/test/scala/ir/ToScalaTest.scala, src/test/scala/test_util/BASILTest.scala
Transforms memory accesses to register assignments using the results of DSA when --memory-transform flag is set
(requires --simplify and --dsa norm)
- creates a global graph (single global region node) and uses it to propagate global constraints among graphs of all procedures 
- replaces memory stores to stack only regions with local assignments
- replaces memory stores to global only regions with memory assignments
- Adds invariant to check unresolved expressions are only used in memory accesses that are unreachable
- transforms memory accesses by splitting the memory to disjoint regions using Data structure analysis results
- determines which values escape a procedure using DSA flags
=> Memory transform

src/main/scala/translating/GTIRBLoader.scala
ASLp will begin producing unsigned division operations as `udiv_bits` once the following is merged: https://github.com/UQ-PAC/aslp/pull/136
This PR adds support for the primitive ahead of time.
=> Add unsigned division to GTIRB loader

src/main/scala/analysis/CommonDefinitionVariableRenaming.scala, src/main/scala/analysis/IntraLiveVarsAnalysis.scala, src/main/scala/analysis/MemoryRegionAnalysis.scala, src/main/scala/ir/IRCursor.scala, src/main/scala/ir/dsl/DSL.scala, src/main/scala/ir/eval/InterpretBasilIR.scala, src/main/scala/ir/transforms/ProcedureParameters.scala, src/main/scala/ir/transforms/Simp.scala, src/main/scala/translating/IRExpToSMT2.scala, src/main/scala/translating/IRToBoogieNoVC.scala, src/main/scala/translating/PrettyPrinter.scala, src/main/scala/util/RunUtils.scala
Updates the various transforms to handle the new `MemoryAssign` sensibly, at least as long as they produced match exhaustivity warnings. 
Also fixes the substitution loop in https://github.com/UQ-PAC/BASIL/issues/401
=> Memtransform fixups

src/main/scala/util/Logging.scala, src/test/scala/LoggingTest.scala
I'm very sorry about this one.
In my changes to GenericLogger to implement the redirection of stdout/stderr (https://github.com/UQ-PAC/BASIL/pull/372), I changed the PrintStream parameter to be a by-name (`=>`) parameter.
This means it is evaluated every time the parameter is used. This was needed to allow for the possibility that Console.out, for example, would be redirected to a new stream.
However, in this instance, it causes problems when the by-name parameter is re-evaluated on every call. Here, the `PrintStream(file)` parameter being re-evaluated means that new PrintStreams are being constructed on the same file, leading to conflicts when flushing and closing, and extremely surprising behaviour.
This was a nasty one, I'm sorry. I would support bigger changes to deriveLogger to …
=> fix GenericLogger.writeToFile bug which produced empty file

src/main/scala/Main.scala
the biggest change is to use the java.nio.file.Path abstraction (https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html) instead of manually manipulating slashes. this should make it more robust on different platforms, and more reasonable in the face of paths which contain semantically equivalent but syntactically different paths (e.g., multiple slashes in a row `//` or `.` path components).
it also improves readability by using methods with path-specific names instead of manipulating lists and strings. some other changes to add more comments and use more functional programming.
in most cases, the new behaviour should be equivalent to the old one. in cases with elements like `//` or `.`, the behaviour should be more reasonable - now, it correctly treats those as insignificant.
=> refactor: improve error messages of loadDirectory and refactor

src/main/scala/boogie/BExpr.scala, src/main/scala/boogie/FunctionOps.scala
Prevent z3 from finding an incorrect interpretation of booltobv1 function
=> mark booltobv1 function inline

.github/workflows/run-examples.yml, src/main/scala/ir/dsl/DSL.scala
Works on Linux but causes tests to fail to compile on case-insensitive filesystems.
```
[warn] -- Warning: /home/am/Documents/programming/2024/basil-fix-x/src/main/scala/ir/dsl/DSL.scala:200:11 
[warn] 200 |case class Call(target: String, actualParams: (String, Expr)*)
[warn]     |           ^
[warn]     |Generated class ir.dsl.Call differs only in case from ir.dsl.call (defined in InfixConstructors.scala).
[warn]     |  Such classes will overwrite one another on case-insensitive filesystems.
[warn] there were 2 feature warnings; re-run with -feature for details
[warn] three warnings found
```
The lowercase `ir.dsl.call` breaks capital camel case naming convention for classes but in this case its part of the DSL so obscuring that its a class is fine.
I would also set this warning to error …
=> remove duplicate call class

src/test/scala/SystemTests.scala
Working now with fixed SCC function,  this comment remains in the test definition so I'm not sure if its a valid test,
```
// TODO currently procedure_summary3 verifies despite incorrect procedure summary analysis
// this is due to BASIL's currently limited handling of non-returning calls
``
=> re-enable procedure_summary3

build.sc
I'm working on migrating the Nix package to use mill. This version number will need to be updated manually whenever the Scala version is changed.
Without this change, it fails with this error:
```
basil-sbt-dependencies.tar.zst> Preparing Java 17.0.13 runtime; this may take a minute or two ...
basil-sbt-dependencies.tar.zst> [info] compiling 2 Scala sources to /build/source/out/mill-build/compile.dest/classes ...
basil-sbt-dependencies.tar.zst> [info] done compiling
basil-sbt-dependencies.tar.zst> Resolving Ammonite Repl 3.0.0-M0-53-084f7f4e for Scala 3.3.4 ...
basil-sbt-dependencies.tar.zst> If you encounter dependency resolution failures, please review/override `def ammoniteVersion` to select a compatible release.
basil-sbt-dependencies.tar.zst> 1 targets failed …
```
=> set ammoniteVersion in build.sc

src/main/scala/analysis/GammaDomains.scala, src/main/scala/analysis/IrreducibleLoops.scala, src/main/scala/analysis/KnownBits.scala, src/main/scala/analysis/Lattice.scala, src/main/scala/analysis/NumericalDomains.scala, src/main/scala/analysis/procedure_summaries/Predicate.scala, src/main/scala/analysis/rely_guarantee_generation/InterferenceDomains.scala, src/main/scala/boogie/BExpr.scala, src/main/scala/ir/Expr.scala, src/main/scala/ir/IRType.scala, src/main/scala/ir/dsl/DSL.scala, src/main/scala/ir/dsl/InfixConstructors.scala, src/main/scala/ir/eval/BitVectorEval.scala, src/main/scala/ir/eval/ExprEval.scala, src/main/scala/ir/eval/SimplifyExpr.scala, src/main/scala/ir/transforms/IndirectCallResolution.scala, src/main/scala/ir/transforms/LinuxAssertFail.scala, src/main/scala/ir/transforms/ReplaceReturn.scala, src/main/scala/translating/BAPToIR.scala, src/main/scala/translating/GTIRBLoader.scala, src/main/scala/translating/GTIRBToIR.scala, src/main/scala/translating/IRExpToSMT2.scala, src/main/scala/translating/IRToBoogie.scala, src/main/scala/translating/SpecificationLoader.scala, src/test/scala/BitVectorSMTTest.scala, src/test/scala/ConditionLiftingTests.scala, src/test/scala/InterpretTestConstProp.scala, src/test/scala/SATTest.scala, src/test/scala/TestKnownBitsInterpreter.scala, src/test/scala/ir/InterpreterTests.scala
This removes the duplicate EQ ops BVEQ, BoolEQ, IntEQ, BoolEQUIV and the NEQ equivalends and replaces them with a single `EQ` and `NEQ` operator. This generally reduces the number of cases to write and makes it possible to compare any type (as it is in boogie and smt).
=> remove duplicate eq ops

src/main/scala/ir/IRCursor.scala
This hopefully prevents the non-determinism in computeDomain in IRCursor, which seems to have been caused by iterating over a set while modifying it, which is undefined behaviour (and in practice seems to be non-deterministic).
computeDomain is used everywhere in the analyses so this is likely the source of most of the non-determinism issues we've been having.
=> computeDomain non-determinism

build.mill
previously, in pages like
https://uq-pac.github.io/BASIL/api/basil/ir/parsing/BasilEarlyBNFCVisitor.html,
the links to bnfc-generated classes like Visitor would not work. this fixes those links.
old:
new:
=> docs: fix cross-linking to bnfc javadocs

src/main/scala/ir/dsl/DSL.scala, src/main/scala/ir/transforms/Inline.scala, src/test/scala/ir/IRTest.scala
Caches the `label -> block` and `name -> procedure` mapping to avoid linear search.
The tests just reconstruct this cache every time as they usually modify the procedure and incrementally resolve.
=> use hashmap to improve dsl loading perf by 2000%

src/main/scala/Main.scala
previously, when running
./mill run --load-directory-gtirb asdf.gts
to load files from the current directory, you would see an error:
Exception in thread "main" java.lang.NullPointerException:
Cannot invoke "java.nio.file.Path.getFileName()" because
the return value of "java.nio.file.Path.getParent()" is null
at Main$.loadDirectory(Main.scala:45)
at Main$.main(Main.scala:283)
at Main.main(Main.scala)
this pr fixes using --load-directory without any directory prefix, by assuming the current working directory.
previously, this could also be worked around by using
./mill run --load-directory-gtirb ./asdf.gts
=> fix bug when using --load-directory with a filename in the current dir

src/main/scala/Main.scala
assuming you had files atomic.-O0.gts  atomic.-O0.relf  atomic.-O0.spec in a directory, previously, this would not work:
./mill run --load-directory-gtirb atomic/atomic/atomic.-O0.gts
the logic would incorrectly replace /two/ levels of file extension and look for files named atomic.gts and atomic.relf.
this fixes the logic to only strip off one file extension.
a test case is this zip from Aaron:
https://github.com/user-attachments/files/20717350/atomic.zip
=> fix --load-directory when used with filenames with multiple dots

src/main/scala/translating/GTIRBToIR.scala
allows TempIf to occur in the middle of blocks, but only if both sides of the tempif branch or both sides do not branch.
this allows handling of, for example, `casal w0, w4, [x3]` 0x88e0fc64 which looks like this:
```
AtomicStart.0 {{  }} (  ) ;
constant bits ( 32 ) Exp16__6 = Mem.read.0 {{ 4 }} ( __array _R [ 3 ],4,9 ) ;
if eq_bits.0 {{ 32 }} ( Exp16__6,__array _R [ 0 ] [ 0 +: 32 ] ) then {
Mem.set.0 {{ 4 }} ( __array _R [ 3 ],4,9,__array _R [ 4 ] [ 0 +: 32 ] ) ;
}
AtomicEnd.0 {{  }} (  ) ;
__array _R [ 0 ] = ZeroExtend.0 {{ 32,64 }} ( Exp16__6,64 ) ;
```
i wish i could write a unit test for this, but alas...
Fixes: https://github.com/UQ-PAC/BASIL/issues/454
=> allow TempIf in the middle of blocks, given unique branching behaviour

scripts/liftmake.sh, src/main/scala/Main.scala, src/main/scala/translating/GTIRBToIR.scala, src/main/scala/util/BASILConfig.scala, src/main/scala/util/RunUtils.scala, src/test/scala/DataStructureAnalysisTest.scala, src/test/scala/DifferentialAnalysisTest.scala, src/test/scala/InterpretTestConstProp.scala, src/test/scala/IntervalDSATest.scala, src/test/scala/IrreducibleLoop.scala, src/test/scala/MemoryTransformTests.scala, src/test/scala/PCTrackingTest.scala, src/test/scala/RemovePCTest.scala, src/test/scala/SVATest.scala, src/test/scala/ir/IRToDSLTest.scala, src/test/scala/ir/InterpreterTests.scala, src/test/scala/test_util/BASILTest.scala
Make --relf optional for tasks not requiring symbols. The symbol table is only really required for the spec input and DSA heuristics and the relf parser tends to be by far the most fragile part of the frontend.
When relf is not provided look for `--main-procedure-name` (default 'main') in the procedure list to set as Program.mainProcedure. This is previously all we do to detect the entrypoint, except with the relf symbol table to find a procedure address to search for.
I think eventually we should be able to retrieve all the same information from the gtirb `Module.symbols` but that's a bigger task.
=> Make --relf optional

.github/workflows/run-examples.yml, scripts/scalatest.sh, src/test/scala/DifferentialAnalysisTest.scala, src/test/scala/IntervalDSATest.scala, src/test/scala/SystemTests.scala, src/test/scala/test_util/BASILTest.scala, src/test/scala/test_util/tags/AnalysisSystemTest2.java, src/test/scala/test_util/tags/AnalysisSystemTest3.java, src/test/scala/test_util/tags/AnalysisSystemTest4.java
this brings back the old scalatest.sh which directly invokes scalatest's runner. now that there's a case fallback if MILL_WORKSPACE_ROOT is unset, this seems to work fine and leads to the best behaviour:
tests are run all in one thread, allowing for the best runtime performance and correctly-sorted output.
for reference:
- commit before mill 12.10 and scalatest.sh removal https://github.com/UQ-PAC/BASIL/commit/55587f08f4f90ecd35e86c14c8729669f67ca0b3
- my unfortunate suggestion to use `./mill test` directly https://github.com/UQ-PAC/BASIL/pull/421#issuecomment-2861915997
- hacky band-aid by re-sorting output. this worked but it was slow. https://github.com/UQ-PAC/BASIL/pull/429
i'm sorry for the trouble lol
=> ci: use scalatest runner directly (again)

src/main/scala/Main.scala, src/main/scala/ir/transforms/Simp.scala, src/test/scala/ConditionLiftingTests.scala
Implements a more standard implementation of flow-insensitive copyprop (disabled) as well as a similar transform targeted specifically at address calculations: for values conforming to a (variable + constant) structure. 
By deferring substitution we avoid tracking clobbers so this is >2x faster than the existing 'DSACopyProp', and is more effective at removing redundant dsa copies involved in loops. It is still sufficient to fully propagate through stack address calculations so none of the tests should timeout. 
This does not handle propagating flag calculations at all, so that relies entirely on https://github.com/UQ-PAC/BASIL/pull/413
note: translation validation succeeds for this program https://github.com/UQ-PAC/basil-tests/blob/main/src/test/csmith/csmith4/csmith4.c#L3552-L3601
=> simplify: implement standard copyprop

.github/workflows/docs.yml, .github/workflows/run-examples.yml, basilmill/bnfc.mill, build.mill, docs/static/index.html
This processes the BNFC grammar through its Latex output and converts that to HTML using lwarp. This is added to the Basil docs website.
This makes the docs building process more complicated, since it needs texlive. The Github Actions are split up to factor out the apt installations. The test workflow now invokes the docs.yml workflow.
=> add HTML and PDF output for the BNFC grammar

src/main/scala/ir/invariant/Typecheck.scala, src/main/scala/util/RunUtils.scala
Cheap validation that the IR is well-formed at a superficial level, will hopefully aid in validating front-ends and transforms.
This is specifically motivated by validating the offline lifter without relying on Boogie.
This generally works by iterating through the IR and checking for type errors, which is prone to incompleteness. Basil's type system is simple enough it should be possible to make this complete but I don't really have a good way to encode guardrails against missing possible type errors.
=> Basic type checker for Basil IR

docs/src/SUMMARY.md, docs/src/quick-lifting.md, docs/src/usage.md, scripts/nix-cc.sh
This PR adds `nix-cc.sh`, a quick method to compile and lift a new example
for use with the Basil toolchain.
This script automates the steps described in [usage.md](usage.md) and automatically
fetches the required tools from the [pac-nix](https://github.com/katrinafyi/pac-nix/) repository.
=> add nix-cc.sh for quickly cross-compiling and lifting examples

src/main/scala/ir/transforms/ProcedureParameters.scala
Don't use `Option.get`: fix for https://github.com/UQ-PAC/BASIL/issues/480
The function that hits the error is our old friend `errorFn`, which does not return. 
```
proc @errorFn_1964 () -> (_PC_out:bv64)
{ .name = "errorFn"; .address = 0x7ac }
[
block %errorFn_entry [
goto(%errorFn_loop1_3);
];
block %errorFn_loop1_3 {.address = 0x7ac; .originalLabel = "wK9NYU4TTr+D8gXPiCk+7w=="} [
goto(%errorFn_loop1_3);
]
];
```
=> procedure params: avoid assuming return block defined

.github/workflows/docs.yml, src/main/scala/gtirb/GTIRBReadELF.scala
this checks for broken links across the github pages site and reports the broken links to the github actions summary.
see: https://lychee.cli.rs/
broken links are not configured to fail the ci build, but we could make it so if it's all cleaned up.
=> ci: add link checker using lychee

scripts/nix-cc.sh
quotation marks added everywhere.
nix doesn't like path literals with spaces, so they're copied into a space-less path before being passed to nix.
=> nix-cc.sh: fix usage when given a path with spaces

.github/workflows/docs.yml
at the moment, https://uq-pac.github.io/BASIL/ is a 404 and the docs are actually uploaded [uq-pac.github.io/BASIL/BASIL](https://uq-pac.github.io/BASIL/BASIL). this is because of a mistake I made.
=> docs: fix extra /BASIL/ in URLs

src/test/scala/SystemTests.scala
with the previous testSuiteSuffix = "", this would clash with the SystemTestsGTIRB and lead to non-deterministic failures when writing the boogie output collided.
removing the override returns to the default implementation, which computes a unique suffix based on the test suite name.
=> tests: unset testSuiteSuffix in SystemTestsGTIRBOfflineLifter

src/main/scala/Main.scala, src/main/scala/gtirb/GTIRBReadELF.scala, src/test/scala/SystemTests.scala
works towards https://github.com/UQ-PAC/BASIL/issues/509
=>  gtsrelf: include `LOCAL` globals, apply `atEnd`, and add flag to throw on mismatch

src/main/scala/ir/Program.scala
avoids running through the replaceJump logic which does a bunch of de-linking and re-linking.
although the `jump_=` also has `j ne _jump` logic, replaceJump would always first set an Unreachable jump, then set the new jump, even if the jumps were the same.
```console
$ b.replaceJump(b.jump)
+ jump = ir.Unreachable@31e3250d 
+ jump = GoTo(returntarget) 
```
=> Block: do not replace jump if the new jump is physically equal

src/test/scala/SystemTests.scala
committed files were re-lifted in https://github.com/UQ-PAC/BASIL/pull/510, so the special case to permit their gtsrelf/oldrelf mismatch is no longer needed.
=> tests: remove nestedifglobal exemption

src/main/scala/boogie/BExpr.scala, src/main/scala/ir/Program.scala, src/main/scala/ir/parsing/Attrib.scala, src/main/scala/specification/Specification.scala, src/main/scala/translating/IRToBoogie.scala, src/main/scala/util/ProductOrdered.scala
in sortProceduresRPO, we use a TreeSet with a custom ordering to
enforce a deterministic ordering of walking when multiple options are
available. we also reason that the `seen` set is increasing
and so the `wl` is always decreasing. therefore, we can use `--=` and
avoid re-creating it every iteration. hopefully this is right.
in the IL's attribute printing, we sort all of the maps and sets before
printing. to do so, we introduce ProductOrdered which makes it easy
to define lexicographic ordering on a case class.
i also remove a problematic `Ordered[SpecGlobalOrAccess]` instance
which only sorted by address.
with this change, the attributes of the .il files are now consistent
between gtsrelf and oldrelf.
however, the block numbering and procedure ordering still changes between old relf and …
=> more deterministic ordering for IL serialise and sortProceduresRPO

.github/workflows/docs.yml, .github/workflows/run-examples.yml
it is ridiculous that we download scala 10x every push. this should also speed up compilation time and scalafmt time by enabling incremental compilation.
=> ci: cache coursier dependencies and mill build directory

basilmill/nativedeps.mill, basilmill/z3.mill, src/main/scala/ir/parsing/BasilEarlyBNFCVisitor.scala, src/main/scala/ir/parsing/BasilMainBNFCVisitor.scala, src/main/scala/ir/parsing/ParseException.scala, src/test/scala/ir/ParserTest.scala
fixes missing case for Decl_UninterpFun by using a wildcard match. starts adding tests for parser aside from round-trip tests.
also adds a parsing exception if no procedures are found, and minorly improves this message.
also removes mill logging for .so file copying
fixes https://github.com/UQ-PAC/BASIL/issues/535
=> fix: parser case for Decl_UninterpFun, minor improvements

build.mill
haoyi [says]:
- Lots of performance optimizations, ~halving the fixed overhead of running a build
- Mill now tab-completes flags like -j or --jobs
it looks like no changes needed
[says]: https://github.com/com-lihaoyi/mill/blob/main/changelog.adoc
=> mill: update to 1.0.3

basilmill/platform.mill
They seem to return `x86_64` not `amd64`.
=> fix detect arch on intel mac

src/main/scala/gtirb/GTIRBReadELF.scala
is R_AARCH64_STATIC the name from readelf? the spec calls it R_AARCH64_ABS64 so i went with that
=> gtsrelf: add support for R_AARCH64_ABS64 (257)

.github/workflows/check-doc-links.sh
every CI run does an unreasonably large amount of work. it is good to reduce false negatives.
previously, we had errors such as this
> # Summary
> 
> | Status         | Count   |
> |----------------|---------|
> | 🔍 Total       | 1252772 |
> | ✅ Successful  | 1231887 |
> | ⏳ Timeouts    | 2       |
> | 🔀 Redirected  | 0       |
> | 👻 Excluded    | 20883   |
> | ❓ Unknown     | 0       |
> | 🚫 Errors      | 0       |
> | ⛔ Unsupported | 0       |
> 
> ## Errors per input
> 
> ### Errors in /api/basil/analysis.html
> 
> * [TIMEOUT] <https://hdl.handle.net/1911/96345> | Timeout
> 
> ### Errors in /api/basil/analysis/Dominators$.html
> 
> * [TIMEOUT] <https://hdl.handle.net/1911/96345> | Timeout
> [Full Github Actions output](https://github.com/UQ-PAC/BASIL/actions/runs/17725197963?check_suite …
=> ci: exclude difficult problematic URL and reduce timeouts

src/main/scala/analysis/IrreducibleLoops.scala, src/main/scala/ir/Program.scala, src/main/scala/ir/Statement.scala, src/test/scala/IrreducibleLoop.scala
loop headers for irreducible loops can be arbitrarily-chosen, and  the order of nextBlocks/prevBlocks affects this choice.
these sets are constructed from an order-retaining LinkedHashSet. however, they need to be immutable so they were previously converted to a HashSet which discards order. i've changed it to ListSet for now which is fine for iteration but slow for membership checks. looking at the current basil, i can't find any membership operations on these sets so it's probably fine.
in future, we could roll our own immutable.LinkedHashSet if the need arises.
i also added some code the the IrreducibleLoops test which lets you observe the different return values from the loop finder. if the assertion is replaced with set equals on the headers, then it will start failing (some of the …
=> Retain order in nextBlocks and prevBlocks
